helm:
  chart_name: "crossplane"
  repo: "https://charts.crossplane.io/stable"
  version: "1.17.2"
  namespace: "crossplane-system"
  install_crds: true
  logging: false

k8s:
  kubeconfig_path: "/Users/denpool/.kube/config"
  kubecontext: "minikube"
  cluster-uri: "https://127.0.0.1:49373"
  admin-token: "eyJhbGciOiJSUzI1NiIsImtpZCI6Imw2M0lpQmZOejlleFpOSFRYVDE3Mm5JWnNnbmVUYnJQN1Y4dmhCWVVmd2sifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzMxNTA1MTk2LCJpYXQiOjE3MzE0MTg3OTYsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6Im1pbmlrdWJlLXNhIiwidWlkIjoiOTI5MDNjZDEtMWQ2NS00NDI1LWFkNjYtYWFmMDlhY2I5M2ZhIn19LCJuYmYiOjE3MzE0MTg3OTYsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0Om1pbmlrdWJlLXNhIn0.WGHox4E8Pt1nBhDhIxVCeGwxq-Sbm4Ve3OXm45fIOPUMfq7bSx4C8rPNimGjVnd7QjtAu8_hIZDDVs8jEMX4RCl4--9CoUx_kUXnfv4-JywD7DaXdiIR5jGeAtEZkcQa-nM3v9-7_GRKl-6hvhpgFjqP0wQYPIT_5G1zkZeeVR-ubCTz7b6ZpK7kbeTKBDg0DOQAATge0r0qfPOVxdXDs663wDYU2Zne878UHLaffFgGyzDoC4jg4qFIiZayI2ELLqu0jRjYhqT87bUsRaVlAm-7Mx2xz9DSxUwBIsl9LHFaYCzVJi2yyllVX2fVAEZD75XNXRxY8PSiQ7I4tGoPWQ"
  logging: false

provider:
  name: "digital_ocean"
  namespace: "crossplane-system"
  provider_config: "/Users/denpool/PycharmProjects/pythonProject/manifests/digital_ocean/digital_ocean_provider.yaml"
  logging: false
