apiVersion: do.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: digital-ocean-provider-config
spec:
  credentials:
    secretRef:
      key: token
      name: provider-do-secret
      namespace: crossplane-system
    source: Secret