apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdroplets.compute.crossplane.io
spec:
  group: compute.crossplane.io
  names:
    kind: XDroplet
    plural: xdroplets
    singular: xdroplet
  claimNames:
    kind: DropletClaim
    plural: dropletclaims
    singular: dropletclaim
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    image:
                      type: string
                      description: "The image to use for the Droplet."
                      default: "ubuntu-20-04-x64"
                    region:
                      type: string
                      description: "The region in which to create the Droplet."
                      default: "nyc1"
                    size:
                      type: string
                      description: "The size of the Droplet."
                      default: "s-1vcpu-1gb"
