apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crossplane-edit
  namespace: default
rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: ["*"]
  # Access to events
  - apiGroups: [""]  # Core API group
    resources: [events]  # Resource type for Kubernetes events
    verbs: [get, list, watch]  # Permissions to retrieve and monitor events


  # Full access to DropletClaim
  - apiGroups: [compute.crossplane.io]  # Custom API group for Crossplane resources
    resources:
      - dropletclaims  # Resource type for DropletClaims in Crossplane
    verbs: ["*"]  # All permissions (create, read, update, delete) for DropletClaims