apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crossplane-edit-binding
  namespace: example-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crossplane-edit
subjects:
  - kind: User
    name: john
    namespace: default