apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crossplane-edit
  namespace: example-namespace
rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: ["*"]
  - apiGroups: [""]
    resources: [events]
    verbs: [get, list, watch]


  - apiGroups: [compute.crossplane.io]
    resources:
      - dropletclaims
    verbs: ["*"]